### ISSUE TITLE
100 TSX FREE BONUS

### ISSUE THREAD

**Issue by manumpak1995** [tradestars-app/testnet-bounty#1]
**i can't redeem my 100 TSX bonus**
A clear and concise description of what the b

**Expected behavior**
A clear and concise description of what you expected to happen
!

[Screenshot_2021-01-25-11-11-04-53](https://user-images.githubusercontent.com/54196371/105660905-aa7db000-5efe-11eb-9875-03034e29d4cf.jpg)

**Smartphone (please complete the following information):**
 - Device: [Android]
 - OS: [V7.2]
 - Browser [Chrome]
 - Version [88.0]

**Comment by chentschel** [comment]
Thanks @manumpak1995 . Issue is fixed. Please kindly send your eth address to 'support [at] tradestars.app' with this issue link .

**Comment by manumpak1995** [comment]
Thanks sir

**Comment by igorodrigues** [comment]
An improvement in the search and filter system would be interesting to improve the user experience. Please see in the prints, that if I filter by POSITION (I have Batsman: 149 results) but if I continue to filter, TEAM (Southern District appears 11 results) and COUNTRY (India: 98 results). The filter search returns me No Results Founds. I believe that the ideal would be to update the results of each filter in real time, improving the user experience.
![Captura de Tela (84)](https://user-images.githubusercontent.com/10155931/105706105-e2312b80-5eef-11eb-82d8-cd492a416efd.png)
![Captura de Tela (83)](https://user-images.githubusercontent.com/10155931/105706109-e3625880-5eef-11eb-9dc3-95605734dd3c.png)
![Captura de Tela (82)](https://user-images.githubusercontent.com/10155931/105706114-e4938580-5eef-11eb-96d3-d71d375459b9.png)
