### ISSUE TITLE
Search Filters Results

### ISSUE THREAD

**Issue by igorodrigues** [tradestars-app/testnet-bounty#4]
**Describe the bug**
Using the filter system, if the user chooses the first filter for example POSITION (Batsman: 149 results) and proceeds to the following filters, for example TEAM (Southern District there are still 11 results) and proceeding to the last COUNTRY filter (India, 98 results appear), but the search returns NO RESULTS FOUND due to the filters, but for the user each filter still appears with results.

**To Reproduce**
Prints attached

**Expected behavior**
would be to update in real time the results of each filter (blue squares) and hiding empty items, improving the user experience

**Screenshots**
Prints attached

**Desktop (please complete the following information):**
 - Windows
 - Edge
 - Last version

![Captura de Tela (84)](https://user-images.githubusercontent.com/10155931/105708486-515c4f00-5ef3-11eb-8d84-8a7f807728af.png)
![Captura de Tela (83)](https://user-images.githubusercontent.com/10155931/105708490-528d7c00-5ef3-11eb-81ad-889d53aab7b9.png)
![Captura de Tela (82)](https://user-images.githubusercontent.com/10155931/105708491-53261280-5ef3-11eb-9638-6eb4f4ddcd2e.png)

**Comment by chentschel** [comment]
@igorodrigues thanks we will have the team to review this.

**Comment by chentschel** [comment]
Closing as fixed in: 

- https://github.com/tradestars-app/tradestars-api/pull/21
- https://github.com/tradestars-app/tradestars-ui/pull/190

 @igorodrigues thanks for reporting. Contact team for bounty reward.

**Comment by igorodrigues** [comment]
igo@igorodrigues.com.br
0xD04433D5a60ADf6410c5b4A546562C18E69c8827
