### ISSUE TITLE
Incorrect Information

### ISSUE THREAD

**Issue by erickmark01** [tradestars-app/testnet-bounty#7]
**Describe the bug**
When entering "my portfolio", the information appears that I have $ 250 in deposits. But I didn't deposit anything.

**To Reproduce**
1. Go to 'My portfolio'
2. See error

**Expected behavior**
I believe that the value should be zero, like the others.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 87.0.4280.141

![Deposits](https://user-images.githubusercontent.com/78039804/105880522-bc954680-6003-11eb-9702-0b127bcd7cef.jpg)

**Comment by chentschel** [comment]
@erickmark01 closing as this is the prefund we're giving to every registered user in the testnet stage.
